=== seamusmcshane/jCompute/schemas/batch.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="BatchParameter">
	<xs:sequence>
		<xs:element name="Type" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="Path" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="GroupName" type="xs:string" minOccurs="0" maxOccurs="1"/>										
		<xs:element name="ParameterName" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="Intial" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="Increment" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="Combinations" type="xs:integer" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="BatchConfig">
	<xs:sequence>
		<xs:element name="BaseScenarioFileName" type="xs:string" minOccurs="1" maxOccurs="1"/>									
		<xs:element name="ItemSamples" type="xs:integer" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="BatchLog">
	<xs:sequence>
		<xs:element name="InfoLog" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
		<xs:element name="ItemLog" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="BatchStats">
	<xs:sequence>
		<xs:element name="Store" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
		<xs:element name="BatchStatsExportDir" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="BatchGroupDir" type="xs:string" minOccurs="0" maxOccurs="1"/>
		<xs:element name="BatchSubGroupDirName" type="xs:string" minOccurs="0" maxOccurs="1"/>										
	</xs:sequence>
</xs:complexType>

	<xs:element name="Batch">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Version" type="xs:string"/>
							<xs:element name="Type" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Config" type="BatchConfig"  minOccurs="1" maxOccurs="1"/>
				<xs:element name="Log" type="BatchLog"  minOccurs="1" maxOccurs="1"/>
				<xs:element name="Stats" type="BatchStats"  minOccurs="1" maxOccurs="1"/>
				<xs:element name="Parameters" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameter"  type="BatchParameter"  minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element> 
			</xs:sequence>
		</xs:complexType>
	</xs:element> 
</xs:schema>

=== seamusmcshane/jCompute/scenarios/Batch/TEST/Test - 64 item Batch.xml
<Batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/batch.xsd">
	<Header>
		<Version>0.01</Version>
		<Type>Batch</Type>
	</Header>
	<Config>
		<BatchDescription>64 Item Test Batch</BatchDescription>
		<BaseScenarioFileName>scenario.xml</BaseScenarioFileName>
		<BatchStatsExportDir>stats/</BatchStatsExportDir>
		<BatchDirName>TEST</BatchDirName>
		<ItemSamples>4</ItemSamples>
	</Config>
	<Parameters>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Predator</GroupName>
			<ParameterName>InitialNumbers</ParameterName>
			<Intial>250</Intial>
			<Increment>250</Increment>
			<Combinations>4</Combinations>
		</Parameter>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Prey</GroupName>
			<ParameterName>InitialNumbers</ParameterName>
			<Intial>250</Intial>
			<Increment>250</Increment>
			<Combinations>4</Combinations>
		</Parameter>
	</Parameters>
</Batch>

=== seamusmcshane/jCompute/scenarios/SAPP/batch/BatchRun-ViewRange-5-100-nohunger-prey.xml
<Batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/batch.xsd">
	<Header>
		<Version>0.01</Version>
		<Type>Batch</Type>
	</Header>
	<Config>
		<BatchDescription>Two species simulations with all view ranges combinations from 5-100 at steps of 5</BatchDescription>
		<BaseScenarioFileName>BatchViewRangeScenario-NoHungerPrey.xml</BaseScenarioFileName>
		<BatchStatsExportDir>stats/</BatchStatsExportDir>
		<BatchDirName>ViewRange-(2-Species-5-100)-nohunger-prey</BatchDirName>
		<ItemSamples>20</ItemSamples>
	</Config>
	<Parameters>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Predator</GroupName>
			<ParameterName>ViewRange</ParameterName>
			<Intial>5</Intial>
			<Increment>5</Increment>
			<Combinations>20</Combinations>
		</Parameter>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Prey</GroupName>
			<ParameterName>ViewRange</ParameterName>
			<Intial>5</Intial>
			<Increment>5</Increment>
			<Combinations>20</Combinations>
		</Parameter>
	</Parameters>
</Batch>

=== seamusmcshane/jCompute/scenarios/SAPP/batch/benchmark/BatchRun-benchmark.xml
<Batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/batch.xsd">
	<Header>
		<Version>0.01</Version>
		<Type>Batch</Type>
	</Header>
	<Config>
		<BatchDescription>Predator/Prey with intiial numbers from 100 to 1000</BatchDescription>
		<BaseScenarioFileName>BatchBenchmarkScenario.xml</BaseScenarioFileName>
		<BatchStatsExportDir>stats/</BatchStatsExportDir>
		<BatchDirName>IntialNumbers-(Predator-Prey-100-1000)</BatchDirName>
		<ItemSamples>10</ItemSamples>
	</Config>
	<Parameters>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Predator</GroupName>
			<ParameterName>InitialNumbers</ParameterName>
			<Intial>100</Intial>
			<Increment>100</Increment>
			<Combinations>10</Combinations>
		</Parameter>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Prey</GroupName>
			<ParameterName>InitialNumbers</ParameterName>
			<Intial>100</Intial>
			<Increment>100</Increment>
			<Combinations>10</Combinations>
		</Parameter>
	</Parameters>
</Batch>

=== seamusmcshane/jCompute/scenarios/Batch/ViewRange/noinital-popboom/BatchRun-PP(2S)-VR(5-100)-PY-HT(100)-sam(10)-prey-speed-(0.72).xml
<Batch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/batch.xsd">
	<Header>
		<Version>0.01</Version>
		<Type>Batch</Type>
	</Header>
	<Config>
		<BatchDescription>
		Predator-Prey scenario with evenly matched species, hunger enabled - varing view range.
		</BatchDescription>
		<BaseScenarioFileName>scenario-prey-speed-(0.72).xml</BaseScenarioFileName>
		<BatchStatsExportDir>stats/</BatchStatsExportDir>
		<BatchDirName>PP(2S)-VR(5-100)-PY-HT(100)-sam(10)-prey-speed-(0.72)</BatchDirName>
		<ItemSamples>10</ItemSamples>
	</Config>
	<Parameters>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Predator</GroupName>
			<ParameterName>ViewRange</ParameterName>
			<Intial>5</Intial>
			<Increment>5</Increment>
			<Combinations>20</Combinations>
		</Parameter>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Prey</GroupName>
			<ParameterName>ViewRange</ParameterName>
			<Intial>5</Intial>
			<Increment>5</Increment>
			<Combinations>20</Combinations>
		</Parameter>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Predator</GroupName>
			<ParameterName>HungerThreshold</ParameterName>
			<Intial>50</Intial>
			<Increment>0</Increment>
			<Combinations>1</Combinations>
		</Parameter>
		<Parameter>
			<Type>Group</Type>
			<Path>Agents.SimpleAgent</Path>
			<GroupName>Prey</GroupName>
			<ParameterName>HungerThreshold</ParameterName>
			<Intial>100</Intial>
			<Increment>0</Increment>
			<Combinations>1</Combinations>
		</Parameter>
	</Parameters>
</Batch>
