=== seamusmcshane/jCompute/schemas/sapp-schema.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Scenario">
  <xs:complexType>
    <xs:sequence>
		<xs:element name="Header">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Version" type="xs:string"/>
					<xs:element name="Type" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element> 
		<xs:element name="EndEvents" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Event" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
								<xs:element name="Value" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element> 
		<xs:element name="Statistics" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Stat" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
								<xs:element name="Enabled" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
								<xs:element name="TotalStat" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
								<xs:element name="Graph" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
								<xs:element name="StatSampleRate" type="xs:integer" minOccurs="1" maxOccurs="1"/>
								<xs:element name="GraphSampleWindow" type="xs:integer" minOccurs="1" maxOccurs="1"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>			
		</xs:element> 
		<xs:element name="World">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="Type" type="xs:string"/>
					<xs:element name="Size" type="xs:integer"/>
					<xs:element name="Barriers" type="xs:integer"/>
					<xs:element name="BarriersScenario" type="xs:integer"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element> 		
		<xs:element name="Agents" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="SimpleAgent" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
								<xs:element name="Color" minOccurs="1" maxOccurs="1">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Red" type="xs:integer" minOccurs="1" maxOccurs="1"/>
											<xs:element name="Green" type="xs:integer" minOccurs="1" maxOccurs="1"/>
											<xs:element name="Blue" type="xs:integer" minOccurs="1" maxOccurs="1"/>
										</xs:sequence>
									</xs:complexType>
								</xs:element> 							
								<xs:element name="AgentType" type="xs:string" minOccurs="1" maxOccurs="1"/>
								<xs:element name="InitialNumbers" type="xs:integer" minOccurs="1" maxOccurs="1"/>
								<xs:element name="Size" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="Speed" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="ViewRange" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="MovementCost" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="StartingEnergy" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="DigestiveEfficiency" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="HungerThreshold" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="EnergyConsumptionRate" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="ReproductionAndSurvivalDivisor" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="ReproductionCost" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								<xs:element name="RoamMaxMoves" type="xs:integer" minOccurs="0" maxOccurs="1"/>
								<xs:element name="HuntMaxMoves" type="xs:integer" minOccurs="0" maxOccurs="1"/>
								<xs:element name="HuntExitMaxWait" type="xs:integer" minOccurs="0" maxOccurs="1"/>
								<xs:element name="LearnToMoveMax" type="xs:integer" minOccurs="0" maxOccurs="1"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element> 	
				</xs:sequence>
			</xs:complexType>
		</xs:element> 		
		<xs:element name="Plants" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
						<xs:element name="GenericPlant" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Type" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									<xs:element name="InitialNumbers" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									<xs:element name="StartingEnergy" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									<xs:element name="PlantRegeratonRate" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									<xs:element name="PlantRegenerationNSteps" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									<xs:element name="EnergyAbsorptionRate" type="xs:integer" minOccurs="1" maxOccurs="1"/>
									<xs:element name="ReproductionAndSurvivalDivisor" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element> 
</xs:schema>

=== seamusmcshane/jCompute/scenarios/Batch/ViewRange/default-scenario/10000steps/NoHunger/BatchViewRangeScenario-NoHunger.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/sapp-schema.xsd">
	<Header>
		<Version>0.04</Version>
		<Type>SAPP</Type>
	</Header>
	<EndEvents>
		<Event>
			<Name>StepCount</Name>
			<Value>10000</Value>
		</Event>
		<Event>
			<Name>AllPreyLTE</Name>
			<Value>0</Value>
		</Event>
		<Event>
			<Name>AllPredatorsLTE</Name>
			<Value>0</Value>
		</Event>
	</EndEvents>
	<Statistics>
		<Stat>
			<Name>Population</Name>
			<Enabled>false</Enabled>
			<TotalStat>true</TotalStat>
			<Graph>true</Graph>
			<StatSampleRate>100</StatSampleRate>
			<GraphSampleWindow>100</GraphSampleWindow>
		</Stat>
		<Stat>
			<Name>Births-Deaths</Name>
			<Enabled>false</Enabled>
			<TotalStat>false</TotalStat>
			<Graph>true</Graph>
			<StatSampleRate>100</StatSampleRate>
			<GraphSampleWindow>100</GraphSampleWindow>
		</Stat>
		<Stat>
			<Name>AgentEnergyLevels</Name>
			<Enabled>false</Enabled>
			<TotalStat>false</TotalStat>
			<Graph>true</Graph>
			<StatSampleRate>100</StatSampleRate>
			<GraphSampleWindow>100</GraphSampleWindow>
		</Stat>
		<Stat>
			<Name>AgentAge</Name>
			<Enabled>false</Enabled>
			<TotalStat>false</TotalStat>
			<Graph>true</Graph>
			<StatSampleRate>100</StatSampleRate>
			<GraphSampleWindow>100</GraphSampleWindow>
		</Stat>
		<Stat>
			<Name>AgentViewSize</Name>
			<Enabled>false</Enabled>
			<TotalStat>false</TotalStat>
			<Graph>true</Graph>
			<StatSampleRate>100</StatSampleRate>
			<GraphSampleWindow>100</GraphSampleWindow>
		</Stat>
	</Statistics>
	<World>
		<Type>0</Type>
		<Size>1024</Size>
		<Barriers>0</Barriers>
		<BarriersScenario>0</BarriersScenario>
	</World>
	<Agents>
		<SimpleAgent>
			<Name>Predator</Name>
			<Color>
				<Red>255</Red>
				<Green>0</Green>
				<Blue>0</Blue>
			</Color>
			<AgentType>Predator</AgentType>
			<InitialNumbers>100</InitialNumbers>
			<Size>3.5</Size>
			<Speed>1.00</Speed>
			<ViewRange>10</ViewRange>
			<MovementCost>0.033</MovementCost>
			<StartingEnergy>25</StartingEnergy>
			<DigestiveEfficiency>0.5</DigestiveEfficiency>
			<HungerThreshold>100</HungerThreshold>
			<EnergyConsumptionRate>100</EnergyConsumptionRate>
			<ReproductionAndSurvivalDivisor>0.50</ReproductionAndSurvivalDivisor>
			<ReproductionCost>0.55</ReproductionCost>
		</SimpleAgent>
		<SimpleAgent>
			<Name>Prey</Name>
			<Color>
				<Red>0</Red>
				<Green>0</Green>
				<Blue>255</Blue>
			</Color>
			<AgentType>Prey</AgentType>
			<InitialNumbers>800</InitialNumbers>
			<Size>3.5</Size>
			<Speed>0.90</Speed>
			<ViewRange>10</ViewRange>
			<MovementCost>0.033</MovementCost>
			<StartingEnergy>25</StartingEnergy>
			<DigestiveEfficiency>0.4</DigestiveEfficiency>
			<HungerThreshold>100</HungerThreshold>
			<EnergyConsumptionRate>10</EnergyConsumptionRate>
			<ReproductionAndSurvivalDivisor>0.50</ReproductionAndSurvivalDivisor>
			<ReproductionCost>0.50</ReproductionCost>
		</SimpleAgent>
	</Agents>
	<Plants>
		<GenericPlant>
				<Type>0</Type>
				<InitialNumbers>400</InitialNumbers>
				<StartingEnergy>50</StartingEnergy>
				<PlantRegeratonRate>8</PlantRegeratonRate>
				<PlantRegenerationNSteps>1</PlantRegenerationNSteps>
				<EnergyAbsorptionRate>8</EnergyAbsorptionRate>
				<ReproductionAndSurvivalDivisor>0.25</ReproductionAndSurvivalDivisor>
		</GenericPlant>
	</Plants>
</Scenario>
